# Generated by Django 3.2.18 on 2023-05-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel_serviciu', models.CharField(max_length=250)),
                ('Nume', models.CharField(max_length=250)),
                ('Prenume', models.CharField(max_length=250)),
                ('Data_Nasterii', models.CharField(max_length=250)),
                ('Statut', models.CharField(max_length=250)),
                ('Nivel_de_educatie', models.CharField(max_length=250)),
                ('Ocupatie', models.CharField(max_length=250)),
                ('Adresa_de_domiciliu', models.CharField(max_length=250)),
                ('Adresa_de_mail', models.CharField(max_length=250)),
                ('Număr_de_telefon', models.CharField(max_length=250)),
                ('Venit_lunar_mediu_net', models.CharField(max_length=250)),
                ('Gen', models.CharField(max_length=250)),
                ('Preferinta_pentru_gen', models.CharField(max_length=250)),
                ('Vreau_sa_primesc_rezultatele_chestionarelor', models.CharField(max_length=250)),
                ('Sunt_de_acord_cu_termenii_si_conditiile', models.CharField(max_length=250)),
                ('Poza', models.ImageField(blank=True, upload_to='images/')),
                ('Main_Img64', models.TextField()),
            ],
        ),
    ]
