# Generated by Django 3.2.18 on 2023-06-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateivelichro2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Adresa_de_domiciliu',
            new_name='Companie',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Adresa_de_mail',
            new_name='Functie',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Data_Nasterii',
            new_name='Mesaj',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Gen',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Main_Img64',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Nivel_de_educatie',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Nivel_serviciu',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Număr_de_telefon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Ocupatie',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Poza',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Preferinta_pentru_gen',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Statut',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Sunt_de_acord_cu_termenii_si_conditiile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Venit_lunar_mediu_net',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Vreau_sa_primesc_rezultatele_chestionarelor',
        ),
    ]
