# Generated by Django 3.2.18 on 2023-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateivelichro2', '0002_auto_20230603_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Companie',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Functie',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mesaj',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Nume',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Prenume',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='Position',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
